These are the terms and conditions for signing up to the Atlas Young Enterprise website:

1.
Please don't use hate speech or racial slurs as they will get your account removed from the platform.

2.
Please only post things that are relevant to the project on this platform, don't start talking about things that are off topic.


Tasks:
Handle error:
WARNING:root:Exception raised while handling cache file 'C:\Users\PHYSIC~1\AppData\Local\Temp\tmpga6zxe06\ca063cc85377ecf36bbb312fdaf42909'
Traceback (most recent call last):
  File "c:\users\physicsuser\appdata\local\programs\python\python38-32\lib\site-packages\cachelib\file.py", line 228, in set
    os.replace(tmp, filename)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\PHYSIC~1\\AppData\\Local\\Temp\\tmpga6zxe06\\tmp5w7fs37z.__wz_cache' -> 'C:\\Users\\PHYSIC~1\\AppData\\Local\\Temp\\tmpga6zxe06\\ca063cc85377ecf36bbb312fdaf42909'

Found problem: race conditions :(

Resolved using try and except in file.py

complete readme.md.